Repository iamakhileshmishra/Mini_Projects_JavaScript, pull requests merged in 2022-10, with the labels that each got.

#3 updated README.md
  README.md
Labels: hacktoberfest, hacktoberfest-accepted

#4 StopWatch Added using Vanilla Javascript
  StopWatch/README.md
  StopWatch/index.html
  StopWatch/stopwatch.css
  StopWatch/stopwatch.js
Labels: hacktoberfest, hacktoberfest-accepted

#5 Updated the Readme Note Points
  README.md
Labels: hacktoberfest, hacktoberfest-accepted

#7 Improvement: Update Readme [fixes #1]
  README.md
Labels: documentation, hacktoberfest, hacktoberfest-accepted

#11 Added a to-do-list
  to-do-list/htm1.html
Labels: hacktoberfest, hacktoberfest-accepted

#10 Added Calculator using javascript
  Calculater/README.md
  Calculater/calc.css
  Calculater/calc.js
  Calculater/index.html
Labels: hacktoberfest, hacktoberfest-accepted

#15 Dev/navbar a good looking animated darkthemed navbar
  dropdown/README.md
  dropdown/index.html
  dropdown/index.js
  dropdown/styles.css
Labels: hacktoberfest, hacktoberfest-accepted

#16 Add Simon Game
  Simon Game Challenge/index.html
  Simon Game Challenge/index.js
  Simon Game Challenge/sounds/blue.mp3
  Simon Game Challenge/sounds/green.mp3
  Simon Game Challenge/sounds/red.mp3
  Simon Game Challenge/sounds/wrong.mp3
  Simon Game Challenge/sounds/yellow.mp3
  Simon Game Challenge/styles.css
Labels: hacktoberfest, hacktoberfest-accepted

#18 Readme of to do list updated
  to-do-list/README.md
Labels: documentation, hacktoberfest, hacktoberfest-accepted

#19 Pizza Shop Website Added
  Pizza-Shop/css/style.css
  Pizza-Shop/images/about-1.svg
  Pizza-Shop/images/about-2.svg
  Pizza-Shop/images/about-3.svg
  Pizza-Shop/images/home-bg.jpg
  Pizza-Shop/images/home-img-1.png
  Pizza-Shop/images/home-img-2.png
  Pizza-Shop/images/home-img-3.png
  Pizza-Shop/images/pizza-1.jpg
  Pizza-Shop/images/pizza-2.jpg
  Pizza-Shop/images/pizza-3.jpg
  Pizza-Shop/images/pizza-4.jpg
  Pizza-Shop/images/pizza-5.jpg
  Pizza-Shop/images/pizza-6.jpg
  Pizza-Shop/images/pizza-7.jpg
  Pizza-Shop/images/pizza-8.jpg
  Pizza-Shop/images/pizza-9.jpg
  Pizza-Shop/index.html
  Pizza-Shop/js/script.js
Labels: hacktoberfest, hacktoberfest-accepted

#20 feat-add-lift-simulation-project
  lift-simulation/README.md
  lift-simulation/index.html
  lift-simulation/lift.js
  lift-simulation/styles.css
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#22 Minor Uppdate on Ecomerce Diectory
  Ecommerce_Frontend/README.md
Labels: documentation, good first issue, hacktoberfest, hacktoberfest-accepted

#25 Sorting_Visualiser
  Sorting-Visualizer-main/index.html
  Sorting-Visualizer-main/index.js
  Sorting-Visualizer-main/style.css
Labels: hacktoberfest, hacktoberfest-accepted

#24 random quote generator
  Random_Quote_Generator/README.md
  Random_Quote_Generator/css/normalize.css
  Random_Quote_Generator/css/styles.css
  Random_Quote_Generator/index.html
  Random_Quote_Generator/js/script.js
Labels: hacktoberfest, hacktoberfest-accepted

#27 Online Education Website
  online education/css/style.css
  online education/images/about-img.svg
  online education/images/contact-img.svg
  online education/images/course-1.svg
  online education/images/course-2.svg
  online education/images/course-3.svg
  online education/images/course-4.svg
  online education/images/course-5.svg
  online education/images/course-6.svg
  online education/images/homg-img.svg
  online education/images/pic-1.png
  online education/images/pic-2.png
  online education/images/pic-3.png
  online education/images/pic-4.png
  online education/images/pic-5.png
  online education/images/pic-6.png
  online education/images/tutor-1.png
  online education/images/tutor-2.png
  online education/images/tutor-3.png
  online education/images/tutor-4.png
  online education/images/tutor-5.png
  online education/images/tutor-6.png
  online education/index.html
  online education/js/script.js
  real-estate website/css/style.txt
  real-estate website/images/home-bg.jpg
  real-estate website/images/icon-1.png
  real-estate website/images/icon-2.png
  real-estate website/images/icon-3.png
  real-estate website/images/img-1.jpg
  real-estate website/images/img-2.jpg
  real-estate website/images/img-3.jpg
  real-estate website/images/img-4.jpg
  real-estate website/images/img-5.jpg
  real-estate website/images/img-6.jpg
  real-estate website/images/pic-1.png
  real-estate website/images/pic-2.png
  real-estate website/images/pic-3.png
  real-estate website/images/pic-4.png
  real-estate website/images/s-1.png
  real-estate website/images/s-2.png
  real-estate website/images/s-3.png
  real-estate website/index.txt
Labels: hacktoberfest, hacktoberfest-accepted

#34 drumkit added
  Drum--kit/images/crash.png
  Drum--kit/images/kick.png
  Drum--kit/images/snare.png
  Drum--kit/images/tom1.png
  Drum--kit/images/tom2.png
  Drum--kit/images/tom3.png
  Drum--kit/images/tom4.png
  Drum--kit/index.html
  Drum--kit/index.js
  Drum--kit/sounds/crash.mp3
  Drum--kit/sounds/kick-bass.mp3
  Drum--kit/sounds/snare.mp3
  Drum--kit/sounds/tom-1.mp3
  Drum--kit/sounds/tom-2.mp3
  Drum--kit/sounds/tom-3.mp3
  Drum--kit/sounds/tom-4.mp3
Labels: hacktoberfest, hacktoberfest-accepted

#35 food-api
  food -api/food.jpg
  food -api/index.html
  food -api/script.js
  food -api/style.css
Labels: hacktoberfest, hacktoberfest-accepted

#36 Tic-Tac-Toe game Added
  Tic-Tac-Toe/index.html
  Tic-Tac-Toe/script.js
  Tic-Tac-Toe/style.css
Labels: hacktoberfest, hacktoberfest-accepted

#38 Read me for Calculator
  Calculater/README.md
Labels: hacktoberfest, hacktoberfest-accepted

#39 styles added for drumkit
  Drum--kit/index.css
Labels: hacktoberfest, hacktoberfest-accepted

#40 BlackJack game
  blackJackgame/index.html
  blackJackgame/index.js
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#42 added css file
  blackJackgame/index.css
  blackJackgame/index.html
Labels: hacktoberfest, hacktoberfest-accepted

#43 changed background color
  food-api/food.jpg
  food-api/index.html
  food-api/script.js
  food-api/style.css
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#44 Keyboard Project
  keyboard-master/index.html
  keyboard-master/script.js
  keyboard-master/style.css
Labels: hacktoberfest, hacktoberfest-accepted

#45 Created Readme For Drum--kit
  Drum--kit/Readme.md
Labels: documentation, enhancement, hacktoberfest, hacktoberfest-accepted

#46 Grid Size Updated in order to have responsiveness
  Calculater/calc.css
Labels: enhancement, hacktoberfest-accepted

#48 added 2 pro
  3d-boxes-background/index.html
  3d-boxes-background/script.js
  3d-boxes-background/style.css
  animated-countdown/index.html
  animated-countdown/script.js
  animated-countdown/style.css
Labels: hacktoberfest, hacktoberfest-accepted

#49 add +1
  dad-jokes/index.html
  dad-jokes/script.js
  dad-jokes/style.css
Labels: hacktoberfest, hacktoberfest-accepted
